import{S as g,i as m,a as y}from"./assets/vendor-89feecc5.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const e={searchForm:document.querySelector(".search-form"),photoList:document.querySelector(".photo-list"),loader:document.querySelector(".loader"),loaderBottom:document.querySelector(".loader-before-button"),loadMoreBtn:document.querySelector(".fetch-more-button")},l="is-hidden",L=new g(".photo-list a",{captions:!0,captionsData:"alt",captionDelay:250});let i=1,c="",u=0;const b="https://pixabay.com/api",w="41870399-9b44301246ceb98c07efd626a";e.searchForm.addEventListener("submit",B);async function B(r){r.preventDefault(),e.photoList.innerHTML="",e.loader.classList.remove(l),i=1;const a=r.currentTarget;if(c=a.elements.query.value,c===""){e.loadMoreBtn.classList.add(l),e.loader.classList.add(l),m.show({message:"Please enter your request",position:"topRight",color:"yellow"});return}try{const{hits:o,totalHits:n}=await f(c);console.log(n),u=Math.ceil(n/40),console.log(u),h(o,e.photoList),L.refresh(),o.length>0&&o.length!==n?(e.loadMoreBtn.classList.remove(l),e.loadMoreBtn.addEventListener("click",p)):e.loadMoreBtn.classList.add(l)}catch(o){console.log(o.message)}finally{e.loader.classList.add(l),a.reset()}}async function f(r,a=1){return(await y.get(`${b}/?key=${w}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&per_page=40&page=${a}`)).data}async function p(){e.loadMoreBtn.disabled=!0,i+=1,e.loaderBottom.classList.remove(l);try{const{hits:r}=await f(c,i);h(r,e.photoList)}catch(r){console.log(r)}finally{e.loaderBottom.classList.add(l),e.loadMoreBtn.disabled=!1,i===u&&(e.loadMoreBtn.classList.add(l),e.loadMoreBtn.removeEventListener("click",p),m.show({title:"❌",messageColor:"white",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",color:"red"}))}}function h(r){const a=r.map(o=>`<li class="gallery-item">
<a class="gallery-link" href="${o.largeImageURL}">
<img class="gallery-image" ;
    src="${o.webformatURL}"
    data-source="${o.largeImageURL}"
   alt="${o.tags}" />
   </a>
    <p>Likes: ${o.likes}</p>
   <p>Views: ${o.views}</p>
   <p>Comment: ${o.comments}</p>
   <p>Downloads: ${o.downloads}</p>
</li>`).join("");e.photoList.innerHTML=a}
//# sourceMappingURL=commonHelpers.js.map
