import{S as h,i as d,a as y}from"./assets/vendor-89feecc5.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const o={searchForm:document.querySelector(".search-form"),photoList:document.querySelector(".photo-list"),loader:document.querySelector(".loader"),loaderBottom:document.querySelector(".loader-before-button"),loadMoreBtn:document.querySelector(".fetch-more-button")},l="is-hidden",L=new h(".photo-list a",{captions:!0,captionsData:"alt",captionDelay:250});let i=1,c="",m=0;const b="https://pixabay.com/api",w="41870399-9b44301246ceb98c07efd626a";o.searchForm.addEventListener("submit",B);async function B(r){r.preventDefault(),o.photoList.innerHTML="",o.loader.classList.remove(l),i=1;const a=r.currentTarget;if(c=a.elements.query.value,!c){o.loadMoreBtn.classList.add(l),o.loader.classList.add(l),d.show({message:"Please enter your request",position:"topRight",color:"yellow"});return}try{const{hits:e,totalHits:n}=await f(c);console.log(n),m=Math.ceil(n/40),console.log(m),g(e,o.photoList),e.length>0&&e.length!==n?(o.loadMoreBtn.classList.remove(l),o.loadMoreBtn.addEventListener("click",p)):e.length?o.loadMoreBtn.classList.add(l):(o.loadMoreBtn.classList.add(l),d.error({title:"❌",messageColor:"white",message:"Sorry, we dont have any pictures for your request.Please enter correct request!",position:"bottomCenter",color:"red"}))}catch(e){console.log(e)}finally{o.loader.classList.add(l),a.reset()}}async function f(r,a=1){try{const e=await y.get(`${b}/?key=${w}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&per_page=40&page=${a}`);return console.log(e.data),e.data}catch(e){d.error({title:"Error",titleSize:"30",messageSize:"25",message:"Sorry! Try later! Server not working"}),console.error(e.message)}}async function p(){o.loadMoreBtn.disabled=!0,i+=1,o.loaderBottom.classList.remove(l);try{const{hits:r}=await f(c,i);g(r,o.photoList)}catch(r){console.log(r)}finally{o.loaderBottom.classList.add(l),o.loadMoreBtn.disabled=!1,i===m&&(o.loadMoreBtn.classList.add(l),o.loadMoreBtn.removeEventListener("click",p),d.show({title:"❌",messageColor:"white",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",color:"red"}))}}function g(r){const a=r.map(e=>`<li class="gallery-item">
<a class="gallery-link" href="${e.largeImageURL}">
<img class="gallery-image" ;
    src="${e.webformatURL}"
    data-source="${e.largeImageURL}"
   alt="${e.tags}" />
   </a>
    <p>Likes: ${e.likes}</p>
   <p>Views: ${e.views}</p>
   <p>Comment: ${e.comments}</p>
   <p>Downloads: ${e.downloads}</p>
</li>`).join("");o.photoList.insertAdjacentHTML("beforeend",a),L.refresh()}
//# sourceMappingURL=commonHelpers.js.map
